const SUCCESSDOCTORS = "DoctorsTypes@SUCCESSDOCTORS";
const REJECTDOCTORS = "DoctorsTypes@REJECTDOCTORS";
const SUCCESSDOCTORSPROFIL = "DoctorsTypes@SUCCESSDOCTORSPROFIL";
const REJECTDOCTORSPROFIL = "DoctorsTypes@REJECTDOCTORSPROFIL";
const DOCTORSREQUEST = "DoctorsTypes@DOCTORSREQUEST";
const DOCTORSPROFILEREQUEST = "DoctorsTypes@DOCTORSPROFILEREQUEST";
export {
  DOCTORSREQUEST,
  DOCTORSPROFILEREQUEST,
  SUCCESSDOCTORS,
  REJECTDOCTORS,
  SUCCESSDOCTORSPROFIL,
  REJECTDOCTORSPROFIL,
};
