import userImg from "../images/user.png";
import creditCartImg from "../images/credit-card.png";
import helpImg from "../images/help.png";
import logoutImg from "../images/logout.png";
import videoCamImg from "../images/video-camera1.png";
import doctorImg from "../images/doctors.png";
import doctorImg2 from "../images/doctors2.png";
import doctorImg3 from "../images/doctors3.png";
import doctorImg4 from "../images/doctors4.jpg";
import doctorImg5 from "../images/doctors5.jpg";
import doctorImg6 from "../images/doctors6.png";
import doctorImg7 from "../images/doctors7.png";
import doctorImg8 from "../images/doctors8.png";
import doctorImg9 from "../images/doctors9.png";
import doctorImg10 from "../images/doctors10.png";
import doctorImg11 from "../images/doctors11.jpg";
import conversationImg from "../images/conversation.png";
import balanceVisaImg from "../images/visa.png";
import docBalanceImg from "../images/docBalance.png";
import docBalance2Img from "../images/docBalance2.png";

const translateRu = {
  ru: {
    menuItem: [
      {
        menuItem: "Как пользоваться?",
      },
      {
        menuItem: "Мои записи",
      },
      {
        menuItem: "Записаться к врачу",
      },
    ],
    menuProfilName: "Артем Свиридов",
    menuProfilItems: [
      {
        menuProfilitem: "Мой профиль",
        img: userImg,
      },
      {
        menuProfilitem: "Пополнить баланс",
        img: creditCartImg,
      },
      {
        menuProfilitem: "FAQ",
        img: helpImg,
      },
      {
        menuProfilitem: "Выйти",
        img: logoutImg,
      },
    ],
    headerTitle1: `Онлайн консультации`,
    headerTitle2: "от врачей специалистов 24/7",
    headerSubTitle1: "Проконсультируйтесь       ",
    headerSubTitle2: "сейчас",
    headerSubTitle3: "или по",
    headerSubTitle4: "предварительной записи",
    headerSubTitle5:
      "со своего компьютера или c помощью нашего приложения, доступного в",
    headerSubTitle6: "App Store",
    headerSubTitle7: "и",
    headerSubTitle8: "Google Play",
    headerBtn1: "Записаться",
    headerBtn2: "Как это работает?",
    signUpTitle: "Записаться к врачу",
    signUpDesc: "Более 1500 врачей и более 50 разных специализаций",
    signUpList1: "Прием в удобное для вас время, без визита в клинику",
    signUpList2: "Врачи с опытом работы более 8 лет",
    signUpList3:
      "Понятно объясним причину недуга и дадим подробную рекомендацию",
    signUpBtn: "Записаться",
    myNotesTitle: "Мои записи",
    scheduled: "Запланировано",
    past: "Прошедшие",
    canceled: "Отмененные",
    nextEntry: "Ближайшая запись",
    education: "Образование",
    specializes: "Специализируется на лечении",
    additionally: "Дополнительно",
    doctorsText: "Врачи",
    physicianProfile: "Профиль врача",
    doctors: [
      {
        id: 1,
        status: "Запланировано",
        doctorsImg: doctorImg,
        name: "Ольга Никитина",
        profession: "Педиатр",
        experience: "Стаж 15 лет",
        day: "03 Марта 2021",
        hour: "16:00",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 2,
        status: "Прошедшие",
        doctorsImg: doctorImg2,
        name: "Олимпия Герман",
        profession: "Пневмолог",
        experience: "Стаж 12 лет",
        day: "05 Марта 2021",
        hour: "15:00",
        connection: "Чат",
        connectionImg: conversationImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 3,
        status: "Отмененные",
        doctorsImg: doctorImg3,
        name: "Надежда Коробчан",
        profession: "Онколог",
        experience: "Стаж 14 лет",
        day: "25 Марта 2021",
        hour: "19:00",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 4,
        status: "Запланировано",
        doctorsImg: doctorImg4,
        name: "Наталия Кодряну",
        profession: "Психолог и Психотерапевт",
        experience: "Стаж 18 лет",
        day: "03 Апреля 2021",
        hour: "11:00",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 5,
        status: "Прошедшие",
        doctorsImg: doctorImg5,
        name: "Зинаида Сырбу",
        profession: "Акушер-гинеколог",
        experience: "Стаж 10 лет",
        day: "12 Апреля 2021",
        hour: "14:55",
        connection: "Чат",
        connectionImg: conversationImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 6,
        status: "Отмененные",
        doctorsImg: doctorImg6,
        name: "Ирина Трибой",
        profession: "Педиатр",
        experience: "Стаж 20 лет",
        day: "13 Сентября 2022",
        hour: "14:00",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 7,
        status: "Запланировано",
        doctorsImg: doctorImg7,
        name: "Анжела Селиванова",
        profession: "Терапевт",
        experience: "Стаж 8 лет",
        day: "30 Октября 2022",
        hour: "12:30",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 8,
        status: "Прошедшие",
        doctorsImg: doctorImg8,
        name: "Елена Васильева",
        profession: "Акушер-гинеколог",
        experience: "Стаж 7 лет",
        day: "05 Марта 2023",
        hour: "09:00",
        connection: "Видео связь",
        connectionImg: conversationImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 9,
        status: "Отмененные",
        doctorsImg: doctorImg9,
        name: "Лилия Сарагова",
        profession: "Кардиолог",
        experience: "Стаж 17 лет",
        day: "11 Августа 2021",
        hour: "11:00",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 10,
        status: "Запланировано",
        doctorsImg: doctorImg10,
        name: "Людмила Сурацель",
        profession: "Офтальмолог",
        experience: "Стаж 10 лет",
        day: "23 Ноября 2023",
        hour: "23:00",
        connection: "Видео связь",
        connectionImg: videoCamImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
      {
        id: 11,
        status: "Прошедшие",
        doctorsImg: doctorImg11,
        name: "Андриан Чириак",
        profession: "Эндокринолог",
        experience: "Стаж 21 лет",
        day: "07 Декабря 2023",
        hour: "15:00",
        connection: "Видео связь",
        connectionImg: conversationImg,
        docBtn1: "Посмотреть запись",
        docBtn2: "Посмотреть постановление",
        price1: "900 ",
        price2: " / консультация",
        time: "30 минут",
        education1: "1992 - Российский Государственный Университет",
        education2: "1994 - Ординатура по специальности «Педиатрия»",
      },
    ],
    footerDesc1:
      "Онлай- консульации специалистов врачей, то что предлагает данный.",
    footerDesc2:
      "В нашем веб и мобильном приложении вы найдете врачей экспертов, которые окажут вам персонализированную помощь онлайн 24/7",
    footerList1: "Как пользоваться",
    footerList2: "FAQ (ответы на вопросы)",
    footerList3: "Для врачей",
    footerList4: "О сервисе",
    footerList5: "Контакты",
    footerList6: "Пользовательское соглашение",
    footerfeedback1: "allodoc@mail.com",
    footerfeedback2: "г. Москва. ул, Ленина 54, офис 51",
    footerfeedback3: "Пн-Вс с 09:00 до 18:00",
    footerfeedback4: "8 800 555 35 35",
    balanceTitle: "Баланс",
    balanceMoney: "1 058,68",
    balanceBtn: "Пополнить счет",
    balanceStory: "История платежей",
    balanceStoryBtn1: "За сегодня",
    balanceStoryBtn2: "За месяц",
    balanceStoryBtn3: "За все время",
    balanceForToday: "За сегодня",
    balancePerMonth: "За месяц",
    balanceInAll: "За все время",
    balanceData: [
      {
        id: 1,
        status: "За сегодня",
        img: balanceVisaImg,
        time: "10.03.2021",
        title: "Пополнение",
        price: "+ 560,00",
      },
      {
        id: 2,
        status: "За месяц",
        img: docBalanceImg,
        time: "10.03.2021",
        title: "Оплата за консультацию",
        price: "- 900,00",
      },
      {
        id: 3,
        status: "За сегодня",
        img: docBalance2Img,
        time: "10.03.2021",
        title: "Оплата за консультацию",
        price: "- 900,00",
      },
      {
        id: 4,
        status: "За сегодня",
        img: balanceVisaImg,
        time: "10.03.2021",
        title: "Пополнение",
        price: "+ 560,00",
      },
      {
        id: 5,
        status: "За месяц",
        img: balanceVisaImg,
        time: "10.03.2021",
        title: "Пополнение",
        price: "+ 560,00",
      },
      {
        id: 6,
        status: "За месяц",
        img: docBalance2Img,
        time: "10.03.2021",
        title: "Оплата за консультацию",
        price: "- 900,00",
      },
    ],
  },
};

export default translateRu;
