import userImg from "../images/user.png";
import creditCartImg from "../images/credit-card.png";
import helpImg from "../images/help.png";
import logoutImg from "../images/logout.png";
import videoCamImg from "../images/video-camera1.png";
import doctorImg from "../images/doctors.png";
import doctorImg2 from "../images/doctors2.png";
import doctorImg3 from "../images/doctors3.png";
import doctorImg4 from "../images/doctors4.jpg";
import doctorImg5 from "../images/doctors5.jpg";
import doctorImg6 from "../images/doctors6.png";
import doctorImg7 from "../images/doctors7.png";
import doctorImg8 from "../images/doctors8.png";
import doctorImg9 from "../images/doctors9.png";
import doctorImg10 from "../images/doctors10.png";
import doctorImg11 from "../images/doctors11.jpg";
import conversationImg from "../images/conversation.png";
import balanceVisaImg from "../images/visa.png";
import docBalanceImg from "../images/docBalance.png";
import docBalance2Img from "../images/docBalance2.png";
const translateEn = {
  en: {
    menuItem: [
      {
        menuItem: "How to use?",
      },
      {
        menuItem: "My notes",
      },
      {
        menuItem: "To make an appointment with a doctor",
      },
    ],
    menuProfilName: "Artem Sviridov",
    menuProfilItems: [
      {
        menuProfilitem: "My Profile",
        img: userImg,
      },
      {
        menuProfilitem: "Top up balance",
        img: creditCartImg,
      },
      {
        menuProfilitem: "FAQ",
        img: helpImg,
      },
      {
        menuProfilitem: "Exit",
        img: logoutImg,
      },
    ],
    headerTitle1: "Online consultations ",
    headerTitle2: "from specialist doctors 24/7",
    headerSubTitle1: "Consult       ",
    headerSubTitle2: "now",
    headerSubTitle3: "or by",
    headerSubTitle4: "appointment",
    headerSubTitle5: "from your computer or through our app available on the",
    headerSubTitle6: "App Store",
    headerSubTitle7: "and",
    headerSubTitle8: "Google Play.",
    headerBtn1: "Sign up",
    headerBtn2: "How it works?",
    signUpTitle: "Make an appointment",
    signUpDesc:
      "More than 1500 doctors and more than 50 different specialties ",
    signUpList1:
      "Appointments at a time that is convenient for you, without coming to the clinic",
    signUpList2: "Doctors with more than 8 years of experience",
    signUpList3:
      "We will explain the cause of the ailment clearly and give a detailed recommendation",
    signUpBtn: "Sign up",
    myNotesTitle: "My notes",
    scheduled: "Scheduled",
    past: "Past",
    canceled: "Canceled",
    nextEntry: "Next entry",
    education: "Education",
    specializes: "Specializes in treating",
    additionally: "Additionally",
    doctorsText: "Doctors",
    physicianProfile: "Physician profile",
    doctors: [
      {
        id: 1,
        status: "Scheduled",
        doctorsImg: doctorImg,
        name: "Olga Nikitina",
        profession: "Pediatrician",
        experience: "15 years of experience",
        day: "March 03, 2021.",
        hour: "16:00",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 2,
        status: "Past",
        doctorsImg: doctorImg2,
        name: "Olimpia Gherman",
        profession: "Pneumologist",
        experience: "12 years of experience",
        day: "March 05, 2021.",
        hour: "15:00",
        connection: "Chat",
        connectionImg: conversationImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 3,
        status: "Canceled",
        doctorsImg: doctorImg3,
        name: "Nadejda Corobcean",
        profession: "Oncologist",
        experience: "14 years of experience",
        day: "March 25, 2021.",
        hour: "19:00",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 4,
        status: "Scheduled",
        doctorsImg: doctorImg4,
        name: "Natalia Codreanu",
        profession: "Psychologist and Psychotherapist",
        experience: "18 years of experience",
        day: "April 03, 2021.",
        hour: "11:00",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 5,
        status: "Past",
        doctorsImg: doctorImg5,
        name: "Zinaida Sârbu",
        profession: "Obstetrician-gynecologis",
        experience: "10 years of experience",
        day: "April 12, 2021.",
        hour: "14:55",
        connection: "Chat",
        connectionImg: conversationImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 6,
        status: "Canceled",
        doctorsImg: doctorImg6,
        name: "Irina Triboi",
        profession: "Pediatrician",
        experience: "20 years of experience",
        day: "September 13, 2022.",
        hour: "14:00",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 7,
        status: "Scheduled",
        doctorsImg: doctorImg7,
        name: "Angela Selivanov",
        profession: "Therapist",
        experience: "8 years of experience",
        day: "October 30, 2022.",
        hour: "12:30",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 8,
        status: "Past",
        doctorsImg: doctorImg8,
        name: "Elena Vasilieva",
        profession: "Obstetrician-gynecologis",
        experience: "7 years of experience",
        day: "March 05, 2023.",
        hour: "09:00",
        connection: "Video link",
        connectionImg: conversationImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 9,
        status: "Canceled",
        doctorsImg: doctorImg9,
        name: "Lilia Șaragov",
        profession: "Cardiologist",
        experience: "17 years of experience",
        day: "Аugust 11, 2021.",
        hour: "11:00",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 10,
        status: "Scheduled",
        doctorsImg: doctorImg10,
        name: "Ludmila Surățel",
        profession: "Ophthalmologist",
        experience: "10 years of experience",
        day: "November 23, 2023.",
        hour: "23:00",
        connection: "Video link",
        connectionImg: videoCamImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
      {
        id: 11,
        status: "Past",
        doctorsImg: doctorImg11,
        name: "Andrian Chiriac",
        profession: "Endocrinologist",
        experience: "21 years of experience",
        day: "December 07, 2023.",
        hour: "15:00",
        connection: "Video link",
        connectionImg: conversationImg,
        docBtn1: "View entry",
        docBtn2: "View the resolution",
        price1: "900 ",
        price2: " / counseling",
        time: "30 minutes",
        education1: "1992 - Russian State University",
        education2: "1994 - Residency in specialty «Pediatrics»",
      },
    ],
    footerDesc1:
      "Online consultations with specialist doctors, what this one offers.",
    footerDesc2:
      "In our web and mobile app, you'll find expert doctors who will provide you with personalized help online 24/7",
    footerList1: "How to use",
    footerList2: "FAQ (answers to questions)",
    footerList3: "For doctors",
    footerList4: "About the service",
    footerList5: "Contacts",
    footerList6: "User Agreement",
    footerfeedback1: "allodoc@mail.com",
    footerfeedback2: "54, Lenina St., Moscow, office 51",
    footerfeedback3: "Mon-Fri from 09:00 to 18:00",
    footerfeedback4: "8 800 555 35 35",
    balanceTitle: "Balance",
    balanceMoney: "1 058,68",
    balanceBtn: "Top up your account",
    balanceStory: "Payment history",
    balanceStoryBtn1: "For today",
    balanceStoryBtn2: "Per month",
    balanceStoryBtn3: "In all that time",
    balanceForToday: "For today",
    balancePerMonth: "Per month",
    balanceInAll: "In all that time",
    balanceData: [
      {
        id: 1,
        status: "For today",
        img: balanceVisaImg,
        time: "10.03.2021",
        title: "Replenishment",
        price: "+ 560,00",
      },
      {
        id: 2,
        status: "Per month",
        img: docBalanceImg,
        time: "10.03.2021",
        title: "Consultation fee",
        price: "- 900,00",
      },
      {
        id: 3,
        status: "For today",
        img: docBalance2Img,
        time: "10.03.2021",
        title: "Consultation fee",
        price: "- 900,00",
      },
      {
        id: 4,
        status: "For today",
        img: balanceVisaImg,
        time: "10.03.2021",
        title: "Replenishment",
        price: "+ 560,00",
      },
      {
        id: 5,
        status: "Per month",
        img: balanceVisaImg,
        time: "10.03.2021",
        title: "Replenishment",
        price: "+ 560,00",
      },
      {
        id: 6,
        status: "Per month",
        img: docBalance2Img,
        time: "10.03.2021",
        title: "Consultation fee",
        price: "- 900,00",
      },
    ],
  },
};
export default translateEn;
